# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 17:24
from __future__ import unicode_literals

import cotidia.cms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False, verbose_name='Active')),
                ('approval_needed', models.BooleanField(default=False)),
                ('template', models.CharField(default='cms/page.html', max_length=250)),
                ('display_title', models.CharField(max_length=250, verbose_name='Display title')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, verbose_name='Unique Page Identifier')),
                ('order_id', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False, verbose_name='Publish this page. The page will also be set to Active.')),
                ('approve', models.BooleanField(default=False, verbose_name='Submit for approval')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('redirect_to_url', models.URLField(blank=True, help_text='Redirect this page to a given URL', verbose_name='Redirect to URL')),
                ('target', models.CharField(choices=[('_self', 'the same window'), ('_blank', 'a new window')], default='_self', max_length=50, verbose_name='Open page in')),
                ('hide_from_nav', models.BooleanField(default=False, verbose_name='Hide from navigation')),
                ('publish_date', models.DateTimeField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'verbose_name': 'Article',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('config', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Article data sets',
                'verbose_name': 'Article data set',
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Page title')),
                ('slug', models.SlugField(max_length=100)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=7, verbose_name='language')),
                ('content', models.TextField(blank=True)),
                ('regions', models.TextField(blank=True)),
                ('images', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_translation_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.Article')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_translation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Translations',
                'verbose_name': 'Translation',
            },
            bases=(models.Model, cotidia.cms.models.PublishTranslation),
        ),
        migrations.AddField(
            model_name='article',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleDataSet'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='redirect_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_to_page', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_pages',
            field=models.ManyToManyField(blank=True, related_name='_article_related_pages_+', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleupdated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together=set([('parent', 'language_code')]),
        ),
    ]
