# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160106_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='order_id',
        ),
    ]
