# Generated by Django 2.0.1 on 2018-08-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180314_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletranslation',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'English')], max_length=7, verbose_name='language'),
        ),
        migrations.DeleteModel(
            name='ArticleDataSet',
        ),
    ]
