# Generated by Django 2.0.1 on 2018-12-20 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("blog", "0006_auto_20180822_0929")]

    operations = [
        migrations.RenameField(
            model_name="articletranslation",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="articletranslation",
            old_name="date_updated",
            new_name="modified_at",
        ),
        migrations.AddField(
            model_name="articletranslation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
    ]
