# Generated by Django 2.1.13 on 2019-10-19 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190602_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletranslation',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='articletranslation',
            old_name='date_updated',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
